## 15.1 错误类型
* 任何时候当你需要一个新的错误类型，都可以用 errors（必须先 import）包的 `errors.New` 函数接收合适的错误信息来创建


## 15.2 Panic
* 在Go语言中 panic 是一个内置函数，用来表示非常严重的不可恢复的错误。

* __必须要先声明 defer__，否则不能捕获到 panic 异常。

* 普通函数在执行的时候发生 panic 了，则开始运行 defer（如有），defer 处理完再返回。

* > 在多层嵌套的函数调用中调用 panic，可以马上中止当前函数的执行，所有的 defer 语句都会保证执行并把控制权交还给接收到 panic 的函数调用者。这样向上冒泡直到最顶层，并执行（每层的） defer，在栈顶处程序崩溃，并在命令行中用传给 panic 的值报告错误情况：这个终止过程就是 panicking。

* 不能随意地用 panic 中止程序，必须尽力补救错误让程序能继续执行。
  
* 自定义包中的错误处理和 panicking，这是所有自定义包实现者应该遵守的最佳实践：
    1. 在包内部，总是应该从 panic 中 recover：不允许显式的超出包范围的 `panic()`
    2. 向包的调用者返回错误值（而不是 panic）。

* recover() 的调用仅当它在 defer 函数中被直接调用时才有效。

* 案例: 15/panic1.go, 15/panic2.go, 15/panic_recover.go


## 15.3 Recover：从 panic 中恢复
* 这个（recover）内建函数被用于从 panic 或 错误场景中恢复：让程序可以从 panicking 重新获得控制权，停止终止过程进而恢复正常执行。

* recover 只能在 defer 修饰的函数中使用：用于取得 panic 调用中传递过来的错误值，__如果是正常执行，调用 recover 会返回 nil__，且没有其它效果

* 总结：panic 会导致栈被展开直到 defer 修饰的 recover() 被调用或者程序中止。

* 案例: 15/recover_form_panic.go


## 15.4 有关于 defer
* 说到错误处理，就不得不提 defer。先说说它的规则：
    * 规则一 当defer被声明时，其参数就会被实时解析;
    * 规则二 defer执行顺序为先进后出;
    * 规则三 defer可以读取有名返回值，也就是可以改变有名返回参数的值。

* 案例见 15/defer_rule1.go, 15/defer_rule2.go, 15/defer_rule3.go
